config/routes.rb
Rails.application.routes.draw do

  resource :informations do
    collection do
      get 'step1'
      get 'step2'
      get 'step3' # ここで、入力の全てが終了する
      post 'confirm' # 確認用ページ
      get 'done' # 登録完了後のページ
    end

  end
  
  devise_for :users, controllers: {
    sessions:      'users/sessions',
    passwords:     'users/passwords',
    registrations: 'users/registrations'
  } 

    resources :parttimes, only: [:new, :create, :show, :delete] do
      collection do
        post 'confirm'
        get 'done'
      end
    end


  devise_for :owners

  root to: 'informations#index'

end

app/controllers/informations_controller.rb
class InformationsController < ApplicationController
  before_action :save_to_session, only: :step2
  before_action :save_to_session_2, only: :step3
  before_action :save_to_session_3, only: :confirm

  def index
    @users = User.all
    @parttimes = Parttime.includes(:user)
  end

  def step1
    @user = User.new
    # 新規インスタンス作成
  end

  def step2
    @user = User.new
    # 新規インスタンス作成
  end

  def step3
    @user = User.new
    # 新規インスタンス作成
  end

  def confirm
    @user.image.save if @user.image.attached?
    @user = User.new(
      firstname: session[:firstname],
      lastname: session[:lastname],
      firstname_kana: session[:firstname_kana],
      lastname_kana: session[:lastname_kana],
      email: session[:email],
      sex: session[:sex],
      password: session[:password],
      password_confirmation: session[:password_confirmation],
      birth_day: session[:birth_day],
      phone_number: session[:phone_number],
      postal_code: session[:postal_code],
      prefecture_id: session[:prefecture_id],
      city: session[:city],
      building: session[:building],
      highschool: user_params[:highschool],
      h_admission: user_params[:h_admission],
      h_graduate: user_params[:h_graduate],
      univercity: user_params[:univercity],
      u_admission: user_params[:u_admission],
      u_graduate: user_params[:u_graduate],
      job_experience: user_params[:job_experience],
      qualification_1: user_params[:qualification_1],
      q_year_1: user_params[:q_year_1],
      qualification_2: user_params[:qualification_2],
      q_year_2: user_params[:q_year_2],
      qualification_3: user_params[:qualification_3],
      q_year_3: user_params[:q_year_3],
      station: user_params[:station],
      spouse: user_params[:spouse]
    )
    if @user.valid?
      render 'confirm'
    else
      render '/informations/step3'
    end
  end

  def create
    @user = User.new(
      firstname: session[:firstname],
      lastname: session[:lastname],
      firstname_kana: session[:firstname_kana],
      lastname_kana: session[:lastname_kana],
      email: session[:email],
      sex: session[:sex],
      password: session[:password],
      password_confirmation: session[:password_confirmation],
      birth_day: session[:birth_day],
      phone_number: session[:phone_number],
      postal_code: session[:postal_code],
      prefecture_id: session[:prefecture_id],
      city: session[:city],
      building: session[:building],
      highschool: session[:highschool],
      h_admission: session[:h_admission],
      h_graduate: session[:h_graduate],
      univercity: session[:univercity],
      u_admission: session[:u_admission],
      u_graduate: session[:u_graduate],
      job_experience: session[:job_experience],
      qualification_1: session[:qualification_1],
      qualification_2: session[:qualification_2],
      qualification_3: session[:qualification_3],
      q_year_1: session[:q_year_1],
      q_year_2: session[:q_year_2],
      q_year_3: session[:q_year_3],
      station: session[:station],
      spouse: session[:spouse]
    )

    render step1_informations_path and return if params[:back]

    if @user.save
      session[:id] = @user.id
      redirect_to done_informations_path
    else
      render '/informations/step1'
    end
  end

  def done
    sign_in User.find(session[:id]) unless user_signed_in?
    session[:firstname].clear
    session[:lastname].clear
    session[:firstname_kana].clear
    session[:lastname_kana].clear
    session[:email].clear
    session[:sex].clear
    session[:password].clear
    session[:password_confirmation].clear
    session[:birth_day].clear
    session[:phone_number].clear
    session[:postal_code].clear
    session[:prefecture_id].clear
    session[:city].clear
    session[:building].clear
    session[:highschool].clear
    session[:h_admission].clear
    session[:h_graduate].clear
    session[:univercity].clear
    session[:u_admission].clear
    session[:u_graduate].clear
    session[:job_experience].clear
    session[:qualification_1].clear
    session[:qualification_2].clear
    session[:qualification_3].clear
    session[:q_year_1].clear
    session[:q_year_2].clear
    session[:q_year_3].clear
    session[:station].clear
    session[:spouse].clear
  end

  def save_to_session
    session[:firstname] = user_params[:firstname]
    session[:lastname] = user_params[:lastname]
    session[:firstname_kana] = user_params[:firstname_kana]
    session[:lastname_kana] = user_params[:lastname_kana]
    session[:email] = user_params[:email]
    session[:sex] = user_params[:sex]
    session[:password] = user_params[:password]
    session[:password_confirmation] = user_params[:password_confirmation]
    session[:birth_day] = Date.new(params[:user]['birth_day(1i)']&.to_i, params[:user]['birth_day(2i)']&.to_i, params[:user]['birth_day(3i)']&.to_i)
    session[:phone_number] = user_params[:phone_number]
    # バリデーションをかけるため、仮でインスタンスに入力値を入れる

    @user = User.new(
      firstname: session[:firstname],
      lastname: session[:lastname],
      firstname_kana: session[:firstname_kana],
      lastname_kana: session[:lastname_kana],
      email: session[:email],
      sex: session[:sex],
      password: session[:password],
      password_confirmation: session[:password_confirmation],
      birth_day: session[:birth_day],
      phone_number: session[:phone_number],
      postal_code: '1234567',
      prefecture_id: '1',
      city: 'shinjyku',
      building: '',
      highschool: 'tokyo',
      h_admission: '2000',
      h_graduate: '',
      univercity: '',
      u_admission: '',
      u_graduate: '',
      job_experience: 'xxx',
      qualification_1: 'aaa',
      qualification_2: 'bbb',
      qualification_3: 'ccc',
      q_year_1: '1',
      q_year_2: '2',
      q_year_3: '3',
      station: 'shinjyku',
      spouse: 'あり'
    )
    # binding.pry
    # インスタンスにバリデーションをかけ、通らなければ1step目のページを再度表示する
    render '/informations/step1' unless @user.valid?(:save_to_session)
  end

  def save_to_session_2
    session[:postal_code] = user_params[:postal_code]
    session[:prefecture_id] = user_params[:prefecture_id]
    session[:city] = user_params[:city]
    session[:building] = user_params[:building]

    @user = User.new(
      firstname: session[:firstname],
      lastname: session[:lastname],
      firstname_kana: session[:firstname_kana],
      lastname_kana: session[:lastname_kana],
      email: session[:email],
      sex: session[:sex],
      password: session[:password],
      password_confirmation: session[:password_confirmation],
      birth_day: session[:birth_day],
      phone_number: session[:phone_number],
      postal_code: session[:postal_code],
      prefecture_id: session[:prefecture_id],
      city: session[:city],
      building: session[:building],
      highschool: 'tokyo',
      h_admission: '2000',
      h_graduate: '',
      univercity: '',
      u_admission: '',
      u_graduate: '',
      job_experience: 'xxx',
      qualification_1: 'aaa',
      qualification_2: 'bbb',
      qualification_3: 'ccc',
      q_year_1: '1',
      q_year_2: '2',
      q_year_3: '3',
      station: 'shinjyku',
      spouse: 'あり'
    )
    render '/informations/step2' unless @user.valid?(:save_to_session_2)
  end

  def save_to_session_3
    session[:highschool] = user_params[:highschool]
    session[:h_admission] = user_params[:h_admission]
    session[:h_graduate] = user_params[:h_graduate]
    session[:univercity] = user_params[:univercity]
    session[:u_admission] = user_params[:u_admission]
    session[:u_graduate] = user_params[:u_graduate]
    session[:job_experience] = user_params[:job_experience]
    session[:qualification_1] = user_params[:qualification_1]
    session[:q_year_1] = user_params[:q_year_1]
    session[:qualification_2] = user_params[:qualification_2]
    session[:q_year_2] = user_params[:q_year_2]
    session[:qualification_3] = user_params[:qualification_3]
    session[:q_year_3] = user_params[:q_year_3]
    session[:station] = user_params[:station]
    session[:spouse] = user_params[:spouse]

    @user = User.new(
      firstname: session[:firstname],
      lastname: session[:lastname],
      firstname_kana: session[:firstname_kana],
      lastname_kana: session[:lastname_kana],
      email: session[:email],
      sex: session[:sex],
      password: session[:password],
      password_confirmation: session[:password_confirmation],
      birth_day: session[:birth_day],
      phone_number: session[:phone_number],
      postal_code: session[:postal_code],
      prefecture_id: session[:prefecture_id],
      city: session[:city],
      building: session[:building],
      highschool: session[:highschool],
      h_admission: session[:h_admission],
      h_graduate: session[:h_graduate],
      univercity: session[:univercity],
      u_admission: session[:u_admission],
      u_graduate: session[:u_graduate],
      job_experience: session[:job_experience],
      qualification_1: session[:qualification_1],
      qualification_2: session[:qualification_2],
      qualification_3: session[:qualification_3],
      q_year_1: session[:q_year_1],
      q_year_2: session[:q_year_2],
      q_year_3: session[:q_year_3],
      station: session[:station],
      spouse: session[:spouse]
    )
    render '/informations/step3' unless @user.valid?(:save_to_session_3)
  end

  private

  # 許可するキーを設定します
  def user_params
    params.require(:user).permit(
      :image,
      :firstname,
      :lastname,
      :firstname_kana,
      :lastname_kana,
      :email,
      :sex,
      :password,
      :password_confirmation,
      :birth_day,
      :phone_number,
      :postal_code,
      :prefecture_id,
      :city,
      :building,
      :highschool,
      :h_admission,
      :h_graduate,
      :univercity,
      :u_admission,
      :u_graduate,
      :job_experience,
      :qualification_1,
      :qualification_2,
      :qualification_3,
      :q_year_1,
      :q_year_2,
      :q_year_3,

app/helpers/informations_helper.rb
module InformationsHelper
end

app/views/informations/confirm.html.erb
<div class="wrapper">

  <div class="header">
    <div class="title">
      応募者エントリーページ
    </div>
  </div>
  <div class="body">
    <div class="leftside">
    </div>
    <div class="center">
      <div class="user-confirmation">
      <%= form_for(@user, url: {controller: 'informations', action: 'create' }) do |f| %>
        <h1><b>以上の内容でお間違いないですか？</b></h1>

    <table class="user-information-box">
      <tbody>
        <tr>
          <th class="detail-user">証明写真(顔がはっきりと見えるもの・画像加工不可)
          </th>
          <td class="detail-value"><%= image_tag @user.image.variant(resize: '100x100') if @user.image.attached?%></td>
        </tr>
        <tr>
          <th class="detail-user">氏名
          <span class="indispensable">必須</span>
          </th>
          <td class="detail-value"><%= @user.firstname %><%= @user.lastname %></td>
        </tr>
        <tr>
          <th class="detail-user">氏名(ふりがな)
          <span class="indispensable">必須</span>
          </th>
          <td class="detail-value"><%= @user.firstname_kana %><%= @user.lastname_kana %></td>
        </tr>
        <tr>
          <th class="detail-user">メールアドレス
          <span class="indispensable">必須</span>
          </th>
          <td class="detail-value"><%= @user.email %></td>
        </tr>
        <tr>
          <th class="detail-user">性別
          <span class="indispensable">必須</span>
          </th>
          <td class="detail-value"><%= @user.sex %></td>
        </tr>
        <tr>
          <th class="detail-user">パスワード
          <span class="indispensable">必須</span>
          </th>
          <td class="detail-value"><%= @user.password %></td>
        </tr>
        <tr>
          <th class="detail-user">生年月日
          <span class="indispensable">必須</span>
          </th>
          <td class="detail-value"><%= @user.birth_day %></td>
        </tr>
        <tr>
          <th class="detail-user">電話番号
          <span class="indispensable">必須</span>
          </th>
          <td class="detail-value"><%= @user.phone_number %></td>
        </tr>
        <tr>
          <th class="detail-user">郵便番号
          <span class="indispensable">必須</span>
          </th>
          <td class="detail-value"><%= @user.postal_code %></td>
        </tr>
        <tr>
          <th class="detail-user">都道府県
          <span class="indispensable">必須</span>
          </th>
          <td class="detail-value"><%= @user.prefecture.name %></td>
        </tr>
        <tr>
          <th class="detail-user">市町村・番地
          <span class="indispensable">必須</span>
          </th>
          <td class="detail-value"><%= @user.city %></td>
        </tr>
        <tr>
          <th class="detail-user">建物名</th>
          <td class="detail-value"><%= @user.building %></td>
        </tr>
        <tr>
          <th class="detail-user">高校名
          <span class="indispensable">必須</span>
          </th>
          <td class="detail-value"><%= @user.highschool %></td>
        </tr>
        <tr>
          <th class="detail-user">入学年度
          <span class="indispensable">必須</span>
          </th>
          <td class="detail-value"><%= @user.h_admission %></td>
        </tr>
        <tr>
          <th class="detail-user">卒業年度</th>
          <td class="detail-value"><%= @user.h_graduate %></td>
        </tr>
        <tr>
          <th class="detail-user">大学名</th>
          <td class="detail-value"><%= @user.univercity %></td>
        </tr>
        <tr>
          <th class="detail-user">入学年度</th>
          <td class="detail-value"><%= @user.u_admission %></td>
        </tr>
        <tr>
          <th class="detail-user">卒業年度</th>
          <td class="detail-value"><%= @user.u_graduate %></td>
        </tr>
        <tr>
          <th class="detail-user">職歴</th>
          <td class="detail-value"><%= @user.job_experience %></td>
        </tr>
        <tr>
          <th class="detail-user">資格(1つ目)</th>
          <td class="detail-value"><%= @user.qualification_1 %></td>
        </tr>
        <tr>
          <th class="detail-user">取得年度(1つ目)</th>
          <td class="detail-value"><%= @user.q_year_1 %></td>
        </tr>
        <tr>
          <th class="detail-user">資格(2つ目)</th>
          <td class="detail-value"><%= @user.qualification_2 %></td>
        </tr>
        <tr>
          <th class="detail-user">取得年度(2つ目)</th>
          <td class="detail-value"><%= @user.q_year_2 %></td>
        </tr>
        <tr>
          <th class="detail-user">資格(3つ目)</th>
          <td class="detail-value"><%= @user.qualification_3 %></td>
        </tr>
        <tr>
          <th class="detail-user">取得年度(3つ目)</th>
          <td class="detail-value"><%= @user.q_year_3 %></td>
        </tr>
        <tr>
          <th class="detail-user">最寄り駅
          <span class="indispensable">必須</span>
          </th>
          <td class="detail-value"><%= @user.station %></td>
        </tr>
        <tr>
          <th class="detail-user">配偶者の有無
            <span class="indispensable">必須</span>
            </th>
          <td class="detail-value"><%= @user.spouse %></td>
        </tr>
      </tbody>
    </table>
    <div class='submit-btn'>
      <%= f.submit "修正する", name: :back, class:'btn' %>
      <%= f.submit "登録する", name:"submit" ,class:'btn' %>
    </div>
<% end %>

        



      </div>
    </div>
  </div>
</div>

app/views/informations/done.html.erb
<div class="wrapper">

  <div class="header">
    <div class="title">
      応募者エントリーページ
    </div>
  </div>

  <div class="body">
    <div class="leftside">
    </div>
      <div class="center">
        <h1><b>登録しました</b></h1>
        <div class='account-page' id='account-page'>
          <%=link_to "トップへ戻る", root_path, class:'btn'%>

          <%=link_to "エントリーへ",  new_parttime_path, class:'btn'%>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/informations/index.html.erb
  <div class="wrapper">
    <div class="header">
    <%= render "shared/header" %>
    </div>
    <div class="body">
      <div class="leftside">
      
      </div>

      <div class="center">
      <% if owner_signed_in? %>
        <div class="welcome-announce">
          <h1>応募者一覧</h1>
        </div>
          <% @users.each do |user| %>
          <li class='list'>
            <%= link_to parttime_path(user) do %>
              <ul class='parttime-img-content'>
              <% if user.image.attached? %>
              <%= image_tag user.image.variant(resize: '200x200'), class: "parttime-img" %>
              <% end %>
              </ul>
            <ul class='parttime-info'>
              <div class='parttime-name'>
                <%= user.firstname %>  <%= user.lastname %> (<%= user.firstname_kana %>  <%= user.lastname_kana %>)
              </div>
            </ul>
          <% end %>
        </li>
        <% end %>
      <% else %>
        <div class="welcome-announce">
        <p>当店の募集要項にご興味をお持ちいただきありがとうございます。</p>
        <p>下記の「エントリー」ボタンより、ご記入をお願い致します。</p>
        </div>
        <div class="welcome-announce">
        <p>※エントリーするためには当サイトでユーザー登録する必要がございます。</p>
        <p>　ユーザー登録がまだの方は以下より登録をお願い致します。</p>
          <div class="little-button">
            <%= link_to 'ユーザー登録', step1_informations_path %>
          </div>
        </div>
      <div class="main-button">
      <% unless user_signed_in? %>
      <%= link_to 'エントリー', new_user_session_path, class:"link" %>
      <% else %>
      <%= link_to 'エントリー', new_parttime_path, class:"link" %>
      <% end %>
        </div>
      <% end %>
      </div>

      <div class="rightside">
       <%= render "shared/rightside" %>
      </div>
    </div>
  </div>

app/views/informations/step1.html.erb
<div class="wrapper">

  <div class="header">
    <div class="title">
      応募者エントリーページ
    </div>
  </div>
  <div class="body">
    <div class="leftside">
      
    </div>
    <div class="center">

      <%= form_for @user, url: step2_informations_path, method: :get do |f| %>
       <%= render 'shared/error', object: f.object %>
        <div class='field'>
          <p>
          <%= f.label "証明写真(顔がはっきりと見えるもの・画像加工不可)"%>
          <%= image_tag @user.image, class:"click-upload" if @user.image.present?%>
          </p>
          <p>クリックしてファイルをアップロード</p>
          <%= f.file_field :image, id:"user-image" %>
          <div id="image-list">
          </div>
      </div>

        <div class='field'>
          <div class='field-label'>
            <%= f.label "姓"%>
            <span class="indispensable">必須</span>
          </div>
          <div class='field-input'>
            <%= f.text_field :firstname, autofocus: true, id: 'registration_firstname' %>
          </div>
        </div>

        <div class='field'>
          <div class='field-label'>
            <%= f.label "名"%>
            <span class="indispensable">必須</span>
          </div>
          <div class='field-input'>
            <%= f.text_field :lastname, autofocus: true, id: 'registration_lastname' %>
          </div>
        </div>

        <div class='field'>
          <div class='field-label'>
            <%= f.label "姓(ふりがな)"%>
            <span class="indispensable">必須</span>
          </div>
          <div class='field-input'>
            <%= f.text_field :firstname_kana, autofocus: true, id: 'registration_firstname_kana' %>
          </div>
        </div>

        <div class='field'>
          <div class='field-label'>
            <%= f.label "名(ふりがな)"%>
            <span class="indispensable">必須</span>
          </div>
          <div class='field-input'>
            <%= f.text_field :lastname_kana, autofocus: true, id: 'registration_lastname_kana' %>
          </div>
        </div>

        <div class='field'>
          <div class='field-label'>
            <%= f.label "メールアドレス"%>
            <span class="indispensable">必須</span>
          </div>
          <div class='field-input'>
            <%= f.email_field :email, id: 'registration_email' %>
          </div>
        </div>

        <div class='field'>
          <div class='field-label'>
            <%= f.label "性別"%>
            <span class="indispensable">必須</span>
          </div>
          <div class='field-input'>
            <%= f.radio_button :sex, "男性" %>
            <%= f.label :sex, "男性", {value: "男性", style: "display: inline-block;"}  %>
            <%= f.radio_button :sex, "女性" %>
            <%= f.label :sex, "女性", {value: "女性", style: "display: inline-block;"}  %>
          </div>
        </div>

        <div class='field'>
          <div class='field-label'>
            <%= f.label "パスワード"%>
            <span class="indispensable">必須</span>
            <i>※英字と数字の両方を含めて8文字以上で設定してください</i>
          </div>
          <div class='field-input'>
            <%= f.password_field :password, autocomplete: "off", id: 'registration_password' %>
          </div>
        </div>

        <div class='field'>
          <div class='field-label'>
            <%= f.label "パスワード (確認用)"%>
            <span class="indispensable">必須</span>

          </div>
          <div class='field-input'>
            <%= f.password_field :password_confirmation, autocomplete: "off", id: 'registration_password_confirmation' %>
          </div>
        </div>

        <div class='field'>
          <div class='field-label'>
          <%= f.label "生年月日" %>
          <span class="indispensable">必須</span>

          </div>
          <div class='field-input'>
          <%= f.date_select :birth_day,
             start_year: Time.now.year - 60, 
             end_year: Time.now.year - 18, 
             default: Date.new(1989, 1, 1), 
             use_month_numbers: true
              %>
          </div>
        </div>

        <div class='field'>
          <div class='field-label'>
            <%= f.label "電話番号(ハイフンなし)"%>
            <span class="indispensable">必須</span>

          </div>
          <div class='field-input'>
            <%= f.text_field :phone_number, id: 'registration_phone_number' %>
          </div>
        </div>


  <%= f.submit '続けて記入する', name:"commit", class:'btn' %>
<% end %>

    </div>
  </div>
</div>

app/views/informations/step2.html.erb
<div class="wrapper">

  <div class="header">
    <div class="title">
      応募者エントリーページ
    </div>
  </div>
  <div class="body">
    <div class="leftside">
      
    </div>
    <div class="center">

      <%= form_for @user, url: step3_informations_path, method: :get do |f| %>
      <%= render 'shared/error', object: f.object %>
        <div class='field'>
          <div class='field-label'>
            <%= f.label "郵便番号(ハイフンなし)"%>
            <span class="indispensable">必須</span>
          </div>
          <div class='field-input'>
            <%= f.text_field :postal_code, autofocus: true, id: 'registration_postal_code' %>
          </div>
        </div>

        <div class='field'>
          <div class='field-label'>
            <%= f.label "都道府県"%>
            <span class="indispensable">必須</span>
          </div>
          <div class='field-input'>
        <%= f.collection_select(:prefecture_id, Prefecture.all, :id, :name, {},) %>
          </div>
        </div>

        <div class='field'>
          <div class='field-label'>
            <%= f.label "市町村・番地"%>
            <span class="indispensable">必須</span>
          </div>
          <div class='field-input'>
            <%= f.text_field :city, autofocus: true, id: 'registration_city' %>
          </div>
        </div>

        <div class='field'>
          <div class='field-label'>
            <%= f.label "建物名"%>
          </div>
          <div class='field-input'>
            <%= f.text_field :building, autofocus: true, id: 'registration_building' %>
          </div>
        </div>

      <%= f.submit '続けて記入する', name:"commit", class:'btn' %>
<% end %>

    </div>
  </div>
</div>

app/views/informations/step3.html.erb
<div class="wrapper">

  <div class="header">
    <div class="title">
      応募者エントリーページ
    </div>
  </div>
  <div class="body">
    <div class="leftside">
      
    </div>
    <div class="center">

      <%= form_for @user, url: confirm_informations_path do |f| %>
      <%= render 'shared/error', object: f.object %>
          <div class='field-label'>
            <%= f.label "高校名"%>
            <span class="indispensable">必須</span>
          </div>
          <div class='field-input'>
            <%= f.text_field :highschool, autofocus: true, id: 'registration_highschool' %>
          </div>

          <div class='field-label'>
            <%= f.label "入学年度"%>
            <span class="indispensable">必須</span>
          </div>
          <div class='field-input'>
            <%= f.select :h_admission,50.years.ago.year..  Date.today.year,prompt:"--",  autofocus: true %>
          </div>

          <div class='field-label'>
            <%= f.label "卒業年度"%>
          </div>
          <div class='field-input'>
            <%= f.select :h_graduate, 50.years.ago.year.. Date.today.year,prompt:"--", autofocus: true %>
          </div>

          <div class='field-label'>
            <%= f.label "大学名"%>
          </div>
          <div class='field-input'>
            <%= f.text_field :univercity, autofocus: true, id: 'registration_univercity' %>
          </div>

          <div class='field-label'>
            <%= f.label "入学年度"%>
          </div>
          <div class='field-input'>
            <%= f.select :u_admission, 50.years.ago.year.. Date.today.year,prompt:"--", autofocus: true %>
          </div>

          <div class='field-label'>
            <%= f.label "卒業年度"%>
          </div>
          <div class='field-input'>
            <%= f.select :u_graduate, 50.years.ago.year.. Date.today.year,prompt:"--", autofocus: true %>
          </div>

          <div class='field-label'>
            <%= f.label "職歴"%>
          </div>
          <div class='field-input'>
            <%= f.text_area :job_experience, autofocus: true, id: 'registration_job_experience' %>
          </div>

          <div class='field-label'>
            <%= f.label "資格(1つ目)"%>
          </div>
          <div class='field-input'>
            <%= f.text_field :qualification_1, autofocus: true, id: 'registration_qualification_1' %>
          </div>

          <div class='field-label'>
            <%= f.label "取得年度(1つ目)"%>
          </div>
          <div class='field-input'>
            <%= f.select :q_year_1, 50.years.ago.year.. Date.today.year,prompt:"--", autofocus: true %>
          </div>

          <div class='field-label'>
            <%= f.label "資格(2つ目)"%>
          </div>
          <div class='field-input'>
            <%= f.text_field :qualification_2, autofocus: true, id: 'registration_qualification_2' %>
          </div>

          <div class='field-label'>
            <%= f.label "取得年度(2つ目)"%>
          </div>
          <div class='field-input'>
            <%= f.select :q_year_2, 50.years.ago.year.. Date.today.year,prompt:"--", autofocus: true %>
          </div>

          <div class='field-label'>
            <%= f.label "資格(3つ目)"%>
          </div>
          <div class='field-input'>
            <%= f.text_field :qualification_3, autofocus: true, id: 'registration_qualification_3' %>
          </div>

          <div class='field-label'>
            <%= f.label "取得年度(3つ目)"%>
          </div>
          <div class='field-input'>
            <%= f.select :q_year_3, 50.years.ago.year.. Date.today.year,prompt:"--", autofocus: true %>
          </div>

          <div class='field-label'>
            <%= f.label "最寄り駅"%>
            <span class="indispensable">必須</span>
          </div>
          <div class='field-input'>
            <%= f.text_field :station, autofocus: true, id: 'registration_station' %>
          </div>

          <div class='field-label'>
            <%= f.label "配偶者の有無"%>
            <span class="indispensable">必須</span>
          </div>
          <div class='field-input'>
            <%= f.radio_button :spouse, "あり" %>
            <%= f.label :spouse, "あり", {value: "あり", style: "display: inline-block;"} %>
            <%= f.radio_button :spouse, "なし" %>
            <%= f.label :spouse, "なし", {value: "なし", style: "display: inline-block;"} %>
          </div>

        <%= f.submit '登録する', name:"commit", class:'btn' %>
      <% end %>

    </div>
  </div>
</div>