config/routes.rb
Rails.application.routes.draw do

  resource :informations do
    collection do
      get 'step1'
      get 'step2'
      get 'step3' # ここで、入力の全てが終了する
      post 'confirm' # 確認用ページ
      get 'done' # 登録完了後のページ
    end

  end
  
  devise_for :users, controllers: {
    sessions:      'users/sessions',
    passwords:     'users/passwords',
    registrations: 'users/registrations'
  } 

    resources :parttimes, only: [:new, :create, :show, :delete] do
      collection do
        post 'confirm'
        get 'done'
      end
    end


  devise_for :owners

  root to: 'informations#index'

end

app/models/parttime.rb
class Parttime < ApplicationRecord
  belongs_to :user, optional: true, foreign_key: true

  with_options presence: true do
    validates :pr_1
    validates :pr_2
    validates :pr_3
  end
end

app/controllers/parttimes_controller.rb
class ParttimesController < ApplicationController
  def index
    @parttimes = Parttime.includes(:user)
  end

  def new
    @parttime = Parttime.new
  end

  def show
    @user = User.find(params[:id])
    @parttime = @user.parttime
    # @parttime = @user.parttime
  end

  def confirm
    @parttime = Parttime.new(
      sun_parttime_in: parttime_params[:sun_parttime_in],
      sun_parttime_out: parttime_params[:sun_parttime_out],
      mon_parttime_in: parttime_params[:mon_parttime_in],
      mon_parttime_out: parttime_params[:mon_parttime_out],
      tue_parttime_in: parttime_params[:tue_parttime_in],
      tue_parttime_out: parttime_params[:tue_parttime_out],
      wed_parttime_in: parttime_params[:wed_parttime_in],
      wed_parttime_out: parttime_params[:wed_parttime_out],
      thu_parttime_in: parttime_params[:thu_parttime_in],
      thu_parttime_out: parttime_params[:thu_parttime_out],
      fri_parttime_in: parttime_params[:fri_parttime_in],
      fri_parttime_out: parttime_params[:fri_parttime_out],
      sat_parttime_in: parttime_params[:sat_parttime_in],
      sat_parttime_out: parttime_params[:sat_parttime_out],
      pr_1: parttime_params[:pr_1],
      pr_2: parttime_params[:pr_2],
      pr_3: parttime_params[:pr_3]
    )

    @parttime.user_id = current_user.id

    session[:user_id] = current_user.id
    session[:sun_parttime_in] = parttime_params[:sun_parttime_in]
    session[:sun_parttime_out] = parttime_params[:sun_parttime_out]
    session[:mon_parttime_in] = parttime_params[:mon_parttime_in]
    session[:mon_parttime_out] = parttime_params[:mon_parttime_out]
    session[:tue_parttime_in] = parttime_params[:tue_parttime_in]
    session[:tue_parttime_out] = parttime_params[:tue_parttime_out]
    session[:wed_parttime_in] = parttime_params[:wed_parttime_in]
    session[:wed_parttime_out] = parttime_params[:wed_parttime_out]
    session[:thu_parttime_in] = parttime_params[:thu_parttime_in]
    session[:thu_parttime_out] = parttime_params[:thu_parttime_out]
    session[:fri_parttime_in] = parttime_params[:fri_parttime_in]
    session[:fri_parttime_out] = parttime_params[:fri_parttime_out]
    session[:sat_parttime_in] = parttime_params[:sat_parttime_in]
    session[:sat_parttime_out] = parttime_params[:sat_parttime_out]
    session[:pr_1] = parttime_params[:pr_1]
    session[:pr_2] = parttime_params[:pr_2]
    session[:pr_3] = parttime_params[:pr_3]

    if @parttime.valid?
      render 'confirm'
    else
      render new_parttime_path
    end
  end

  def create
    @parttime = Parttime.new(
      user_id: session[:user_id],
      sun_parttime_in: session[:sun_parttime_in],
      sun_parttime_out: session[:sun_parttime_out],
      mon_parttime_in: session[:mon_parttime_in],
      mon_parttime_out: session[:mon_parttime_out],
      tue_parttime_in: session[:tue_parttime_in],
      tue_parttime_out: session[:tue_parttime_out],
      wed_parttime_in: session[:wed_parttime_in],
      wed_parttime_out: session[:wed_parttime_out],
      thu_parttime_in: session[:thu_parttime_in],
      thu_parttime_out: session[:thu_parttime_out],
      fri_parttime_in: session[:fri_parttime_in],
      fri_parttime_out: session[:fri_parttime_out],
      sat_parttime_in: session[:sat_parttime_in],
      sat_parttime_out: session[:sat_parttime_out],
      pr_1: session[:pr_1],
      pr_2: session[:pr_2],
      pr_3: session[:pr_3]
    )

    render new_parttime_path and return if params[:back]

    if @parttime.save
      redirect_to done_parttimes_path
    else
      render new_parttime_path
    end
  end

  def done
    sign_out User.find(current_user.id) if user_signed_in?
  end

  private

  def parttime_params
    params.require(:parttime).permit(:sun_parttime_in, :sun_parttime_out, :mon_parttime_in, :mon_parttime_out, :tue_parttime_in, :tue_parttime_out, :wed_parttime_in, :wed_parttime_out, :thu_parttime_in, :thu_parttime_out, :fri_parttime_in, :fri_parttime_out, :sat_parttime_in, :sat_parttime_out, :pr_1, :pr_2, :pr_3).merge(user_id: current_user.id)
  end
end

app/helpers/parttimes_helper.rb
module ParttimesHelper
end

app/views/parttimes/confirm.html.erb
<div class="wrapper">

  <div class="header">
    <div class="title">
      応募者エントリーページ
    </div>
  </div>
  <div class="body">
    <div class="leftside">
    </div>
    <div class="center">
      <div class="parttime-confirmation">
      <%= form_for(@parttime, url: {controller: 'parttimes', action: 'create' }) do |f| %>
        <h1><b>以上の内容でお間違いないですか？</b></h1>

    <table class="parttime-information-box">
      <tbody>
      <tr>
          <th class="detail-user">氏名
          <span class="indispensable">必須</span>
          </th>
          <td class="detail-value"><%= current_user.firstname %><%= current_user.lastname %></td>
        </tr>

        <tr>
          <th class="detail-parttime">日曜
          </th>
          <td class="detail-value"><%= @parttime.sun_parttime_in %>〜<%= @parttime.sun_parttime_out %></td>
        </tr>
        <tr>
          <th class="detail-parttime">月曜
          </th>
          <td class="detail-value"><%= @parttime.mon_parttime_in %>〜<%= @parttime.mon_parttime_out %></td>
        </tr>
        <tr>
          <th class="detail-parttime">火曜
          </th>
          <td class="detail-value"><%= @parttime.tue_parttime_in %>〜<%= @parttime.tue_parttime_out %></td>
        </tr>
        <tr>
          <th class="detail-parttime">水曜
          </th>
          <td class="detail-value"><%= @parttime.wed_parttime_in %>〜<%= @parttime.wed_parttime_out %></td>
        </tr>
        <tr>
          <th class="detail-parttime">木曜
          </th>
          <td class="detail-value"><%= @parttime.thu_parttime_in %>〜<%= @parttime.thu_parttime_out %></td>
        </tr>
        <tr>
          <th class="detail-parttime">金曜
          </th>
          <td class="detail-value"><%= @parttime.fri_parttime_in %>〜<%= @parttime.fri_parttime_out %></td>
        </tr>
        <tr>
          <th class="detail-parttime">土曜
          </th>
          <td class="detail-value"><%= @parttime.sat_parttime_in %>〜<%= @parttime.sat_parttime_out %></td>
        </tr>
        <tr>
          <th class="detail-parttime">【質問】アルバイトに応募しようと思ったきっかけはなんですか？
          <span class="indispensable">必須</span>
          </th>
          <td class="detail-value"><%= @parttime.pr_1 %></td>
        </tr>
        <tr>
          <th class="detail-parttime">【質問】ここでの仕事を通して挑戦したいことは何ですか？
          <span class="indispensable">必須</span>
          </th>
          <td class="detail-value"><%= @parttime.pr_2 %></td>
        </tr>
        <tr>
          <th class="detail-parttime">【質問】趣味は何ですか？
          <span class="indispensable">必須</span>
          </th>
          <td class="detail-value"><%= @parttime.pr_3 %></td>
        </tr>
      </tbody>
    </table>
    <div class='submit-btn'>
      <%= f.submit "修正する", name: :back, class:'btn' %>
      <%= f.submit "登録する", class:'btn' %>
    </div>
<% end %>

        



      </div>
    </div>
  </div>
</div>

app/views/parttimes/done.html.erb
<div class="wrapper">

  <div class="header">
    <div class="title">
      応募者エントリーページ
    </div>
  </div>

  <div class="body">
    <div class="leftside">
    </div>
      <div class="center">
        <h1><b>応募が完了しました</b></h1>
        <div class='account-page' id='account-page'>
          <%=link_to "トップへ戻る", root_path, class:'btn'%>

        </div>
      </div>
    </div>
  </div>
</div>

app/views/parttimes/new.html.erb
<div class="wrapper">

  <div class="header">
    <div class="title">
      応募者エントリーページ
    </div>
  </div>
  <div class="body">
    <div class="leftside">
      
    </div>
    <div class='center'>
      <%= form_for (@parttime), url: confirm_parttimes_path do |f| %>
      <%= render 'shared/error', object: f.object %>
      <div class='input-block'>
       <p>シフト希望時間</p>
        <div class='field'>
          <div class='field-label'>
            <%= f.label "日曜【出勤時間】"%>
          </div>
          <div class='field-input'>
            <%= f.text_field :sun_parttime_in, autofocus: true, id:'registration_sun_parttime_in' %>
          </div>
        </div>

        <div class='field'>
          <div class='field-label'>
            <%= f.label "日曜【退勤時間】"%>
          </div>
          <div class='field-input'>
            <%= f.text_field :sun_parttime_out, autofocus: true, id:'registration_sun_parttime_out' %>
          </div>
        </div>
        <div class='field'>
          <div class='field-label'>
            <%= f.label "月曜【出勤時間】"%>
          </div>
          <div class='field-input'>
            <%= f.text_field :mon_parttime_in, autofocus: true, id:'registration_mon_parttime_in' %>
          </div>
        </div>

        <div class='field'>
          <div class='field-label'>
            <%= f.label "月曜【退勤時間】"%>
          </div>
          <div class='field-input'>
            <%= f.text_field :mon_parttime_out, autofocus: true, id:'registration_mon_parttime_out' %>
          </div>
        </div>

        <div class='field'>
          <div class='field-label'>
            <%= f.label "火曜【出勤時間】"%>
          </div>
          <div class='field-input'>
            <%= f.text_field :tue_parttime_in, autofocus: true, id: 'registration_tue_parttime_in' %>
          </div>
        </div>

        <div class='field'>
          <div class='field-label'>
            <%= f.label "火曜【退勤時間】"%>
          </div>
          <div class='field-input'>
            <%= f.text_field :tue_parttime_out, autofocus: true, id:'registration_tue_parttime_out' %>
          </div>
        </div>

        <div class='field'>
          <div class='field-label'>
            <%= f.label "水曜【出勤時間】"%>
          </div>
          <div class='field-input'>
            <%= f.text_field :wed_parttime_in, autofocus: true, id:'registration_wed_parttime_in' %>
          </div>
        </div>

        <div class='field'>
          <div class='field-label'>
            <%= f.label "水曜【退勤時間】"%>
          </div>
          <div class='field-input'>
            <%= f.text_field :wed_parttime_out, autofocus: true, id:'registration_wed_parttime_out' %>
          </div>
        </div>

        <div class='field'>
          <div class='field-label'>
            <%= f.label "木曜【出勤時間】"%>
          </div>
          <div class='field-input'>
            <%= f.text_field :thu_parttime_in, autofocus: true, id:'registration_thu_parttime_in' %>
          </div>
        </div>

        <div class='field'>
          <div class='field-label'>
            <%= f.label "木曜【退勤時間】"%>
          </div>
          <div class='field-input'>
            <%= f.text_field :thu_parttime_out, autofocus: true, id:'registration_thu_parttime_out' %>
          </div>
        </div>

        <div class='field'>
          <div class='field-label'>
            <%= f.label "金曜【出勤時間】"%>
          </div>
          <div class='field-input'>
            <%= f.text_field :fri_parttime_in, autofocus: true, id:'registration_fri_parttime_in' %>
          </div>
        </div>

        <div class='field'>
          <div class='field-label'>
            <%= f.label "金曜【退勤時間】"%>
          </div>
          <div class='field-input'>
            <%= f.text_field :fri_parttime_out, autofocus: true, id:'registration_fri_parttime_out' %>
          </div>
        </div>

        <div class='field'>
          <div class='field-label'>
            <%= f.label "土曜【出勤時間】"%>
          </div>
          <div class='field-input'>
            <%= f.text_field :sat_parttime_in, autofocus: true, id:'registration_sat_parttime_in' %>
          </div>
        </div>

        <div class='field'>
          <div class='field-label'>
            <%= f.label "土曜【退勤時間】"%>
          </div>
          <div class='field-input'>
            <%= f.text_field  :sat_parttime_out, autofocus: true, id:'registration_sat_parttime_out' %>
          </div>
        </div>
      </div>

      <div class='input-block'>
        <p>〜質問です。詳しい内容につきましては面接の際にお話ししたいので一言でお答えください。〜</p>
        <div class='field'>
          <div class='field-label'>
            <%= f.label "【質問】アルバイトに応募しようと思ったきっかけはなんですか？"%>
            <span class="indispensable">必須</span>
          </div>
          <div class='pr-input'>
            <%= f.text_field :pr_1, autofocus: true, id:'registration_pr_1' %>
          </div>
        </div>

        <div class='field'>
          <div class='field-label'>
            <%= f.label "【質問】ここでの仕事を通して挑戦したいことは何ですか？"%>
            <span class="indispensable">必須</span>
          </div>
          <div class='pr-input'>
            <%= f.text_field :pr_2, autofocus: true, id:'registration_pr_2' %>
          </div>
        </div>

        <div class='field'>
          <div class='field-label'>
            <%= f.label "【質問】趣味は何ですか？"%>
            <span class="indispensable">必須</span>
          </div>
          <div class='pr-input'>
            <%= f.text_field :pr_3, autofocus: true, id:'registration_pr_3' %>
          </div>
        </div>
        <%= f.submit '登録する', class:'btn' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/parttimes/show.html.erb
  <div class="wrapper">
    <div class="header">
    <%= render "shared/header" %>
    </div>
    <div class="body">
      <div class="leftside">
      
      </div>

      <div class="center">
        <div class="user-confirmation">
        <table class="parttime-information-box">
        <tbody>
        <tr>
          <th class="detail-user">証明写真(顔がはっきりと見えるもの・画像加工不可)
          </th>
          <td class="detail-value"><%= image_tag @user.image.variant(resize: '100x100') if @user.image.attached?%></td>
        </tr>
        <tr>
          <th class="detail-user">氏名
          </th>
          <td class="detail-value"><%= @user.firstname %><%= @user.lastname %></td>
        </tr>
        <tr>
          <th class="detail-user">氏名(ふりがな)
          </th>
          <td class="detail-value"><%= @user.firstname_kana %><%= @user.lastname_kana %></td>
        </tr>
        <tr>
          <th class="detail-user">メールアドレス
          </th>
          <td class="detail-value"><%= @user.email %></td>
        </tr>
        <tr>
          <th class="detail-user">性別
          </th>
          <td class="detail-value"><%= @user.sex %></td>
        </tr>
        <tr>
        <tr>
          <th class="detail-user">生年月日
          </th>
          <td class="detail-value"><%= @user.birth_day %></td>
        </tr>
        <tr>
          <th class="detail-user">電話番号
          </th>
          <td class="detail-value"><%= @user.phone_number %></td>
        </tr>
        <tr>
          <th class="detail-user">郵便番号
          </th>
          <td class="detail-value"><%= @user.postal_code %></td>
        </tr>
        <tr>
          <th class="detail-user">都道府県
          </th>
          <td class="detail-value"><%= @user.prefecture.name %></td>
        </tr>
        <tr>
          <th class="detail-user">市町村・番地
          </th>
          <td class="detail-value"><%= @user.city %></td>
        </tr>
        <tr>
          <th class="detail-user">建物名</th>
          <td class="detail-value"><%= @user.building %></td>
        </tr>
        <tr>
          <th class="detail-user">高校名
          </th>
          <td class="detail-value"><%= @user.highschool %></td>
        </tr>
        <tr>
          <th class="detail-user">入学年度
          </th>
          <td class="detail-value"><%= @user.h_admission %></td>
        </tr>
        <tr>
          <th class="detail-user">卒業年度</th>
          <td class="detail-value"><%= @user.h_graduate %></td>
        </tr>
        <tr>
          <th class="detail-user">大学名</th>
          <td class="detail-value"><%= @user.univercity %></td>
        </tr>
        <tr>
          <th class="detail-user">入学年度</th>
          <td class="detail-value"><%= @user.u_admission %></td>
        </tr>
        <tr>
          <th class="detail-user">卒業年度</th>
          <td class="detail-value"><%= @user.u_graduate %></td>
        </tr>
        <tr>
          <th class="detail-user">職歴</th>
          <td class="detail-value"><%= @user.job_experience %></td>
        </tr>
        <tr>
          <th class="detail-user">資格(1つ目)</th>
          <td class="detail-value"><%= @user.qualification_1 %></td>
        </tr>
        <tr>
          <th class="detail-user">取得年度(1つ目)</th>
          <td class="detail-value"><%= @user.q_year_1 %></td>
        </tr>
        <tr>
          <th class="detail-user">資格(2つ目)</th>
          <td class="detail-value"><%= @user.qualification_2 %></td>
        </tr>
        <tr>
          <th class="detail-user">取得年度(2つ目)</th>
          <td class="detail-value"><%= @user.q_year_2 %></td>
        </tr>
        <tr>
          <th class="detail-user">資格(3つ目)</th>
          <td class="detail-value"><%= @user.qualification_3 %></td>
        </tr>
        <tr>
          <th class="detail-user">取得年度(3つ目)</th>
          <td class="detail-value"><%= @user.q_year_3 %></td>
        </tr>
        <tr>
          <th class="detail-user">最寄り駅
          </th>
          <td class="detail-value"><%= @user.station %></td>
        </tr>
        <tr>
          <th class="detail-user">配偶者の有無

            </th>
          <td class="detail-value"><%= @user.spouse %></td>
        </tr>

        <tr>
          <th class="detail-parttime">日曜
          </th>
          <td class="detail-value"><%= @parttime.sun_parttime_in %>〜<%= @parttime.sun_parttime_out %></td>
        </tr>
        <tr>
          <th class="detail-parttime">月曜
          </th>
          <td class="detail-value"><%= @parttime.mon_parttime_in %>〜<%= @parttime.mon_parttime_out %></td>
        </tr>
        <tr>
          <th class="detail-parttime">火曜
          </th>
          <td class="detail-value"><%= @parttime.tue_parttime_in %>〜<%= @parttime.tue_parttime_out %></td>
        </tr>
        <tr>
          <th class="detail-parttime">水曜
          </th>
          <td class="detail-value"><%= @parttime.wed_parttime_in %>〜<%= @parttime.wed_parttime_out %></td>
        </tr>
        <tr>
          <th class="detail-parttime">木曜
          </th>
          <td class="detail-value"><%= @parttime.thu_parttime_in %>〜<%= @parttime.thu_parttime_out %></td>
        </tr>
        <tr>
          <th class="detail-parttime">金曜
          </th>
          <td class="detail-value"><%= @parttime.fri_parttime_in %>〜<%= @parttime.fri_parttime_out %></td>
        </tr>
        <tr>
          <th class="detail-parttime">土曜
          </th>
          <td class="detail-value"><%= @parttime.sat_parttime_in %>〜<%= @parttime.sat_parttime_out %></td>
        </tr>
        <tr>
          <th class="detail-parttime">【質問】アルバイトに応募しようと思ったきっかけはなんですか？
          </th>
          <td class="detail-value"><%= @parttime.pr_1 %></td>
        </tr>
        <tr>
          <th class="detail-parttime">【質問】ここでの仕事を通して挑戦したいことは何ですか？
          </th>
          <td class="detail-value"><%= @parttime.pr_2 %></td>
        </tr>
        <tr>
          <th class="detail-parttime">【質問】趣味は何ですか？
          </th>
          <td class="detail-value"><%= @parttime.pr_3 %></td>
        </tr>
      </tbody>
    </table>
      
        <div class='account-page' id='account-page'>
          <%=link_to "トップへ戻る", root_path, class:'btn'%>
        </div>
      
      </div>
    </div>
  </div>